nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: Movie DB API
            description: An app
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^\/(?!(api\/doc.*|\_.*)$) # Filter out /api/doc and _error pages
